### ISSUE TITLE
Unable to directly spawn gltf that does not require components

### ISSUE THREAD

**Issue by GitGhillie** [kaosat-dev/Blender_bevy_components_workflow#102]
I want to spawn a scene and because of an issue I ran into (https://github.com/Jondolf/bevy_xpbd/issues/304 if you want more context) I figured I would just spawn it directly during Startup, as this scene doesn't have any components that need to be added using bevy_gltf_components. However, this results in a panic with message "this gltf should have been loaded".

It's not too bad to work around but I'm guessing it's not the intended behavior of the crate.

**Comment by czettnersandor** [comment]
@GitGhillie how did you workaround this?

**Comment by GitGhillie** [comment]
> @GitGhillie how did you workaround this?

My idea was to use bevy_asset_loader as I do normally with bevy_gltf_components, and then delay spawning one of the scenes like so:
```rust
.add_systems(OnEnter(GameState::AssetsLoaded), spawn_A)
.add_systems(
    OnEnter(GameState::AssetsLoaded),
    spawn_B.run_if(on_timer(Duration::new(5, 0))),
)
```

However, this does not work and only spawns one of A and B... which means the issue I had with bevy_xpbd is maybe an issue with bevy_asset_loader instead. Need to find a different workaround :(

**Comment by kaosat-dev** [comment]
> I want to spawn a scene and because of an issue I ran into ([Jondolf/bevy_xpbd#304](https://github.com/Jondolf/bevy_xpbd/issues/304) if you want more context) I figured I would just spawn it directly during Startup, as this scene doesn't have any components that need to be added using bevy_gltf_components. However, this results in a panic with message "this gltf should have been loaded".
> 
> It's not too bad to work around but I'm guessing it's not the intended behavior of the crate.

hmm that is a scenario I did not encounter before, thanks for the bug report ! 
I think it might make sense to change the way the gltf loading tracking is handled in ```bevy_gltf_components``` so that it gives you a warning, and does not blow up in your face/panics.
(this is way overdue, as I also want to deal with dropping un-needed gltf handles that are kept around in the asset tracker).

So changing **track_new_gltf** (excuse the poor code quality, very tired & sick)
```
 let handle = asset_server.get_id_handle(*id);
            if let Some(handle) = handle {
                tracker.add_gltf(handle.clone());
                debug!("gltf created {:?}", handle.clone());
            }else {
                warn!("this gltf should have been loaded, no handle available, not processing it")
            }
            ```

**Comment by GitGhillie** [comment]
That seems to do the trick! Now I'm running into an issue where the scene loaded with the asset loader only rarely shows up, but I think that's then something to do with bevy_asset_loader.

**Comment by kaosat-dev** [comment]
@GitGhillie is its a random failure of a scene to show up ?
I had such issues back in Bevy 0.11 where scenes would get randomly unloaded directly after being loaded, had not had those issues since then.
Have you tried forcing the creation of a strong handle manually to prevent the issue ?

**Comment by GitGhillie** [comment]
I made a minimal example to illustrate the problem I'm having with bevy/bevy_asset_loader: https://github.com/GitGhillie/asset_loading_mre/blob/main/src/main.rs

Not sure how to manually create a strong handle but appending #Scene0 to the paths fixes the scenes randomly getting swapped. With my Bevy 0.11 project I was already doing this but now with 0.12 it seems like bevy_gltf_components doesn't work when a scene is spawned with #Scene0. I'm getting "this gltf should have been loaded, no handle available, not processing it" from your hotfix.

**Comment by kaosat-dev** [comment]
@GitGhillie I suddenly remembered that I faced this issue as well !
When using #scene it unloads the gltf file, the handle is lost, that is why I switched to loading the full gltf files in the [examples](https://github.com/kaosat-dev/Blender_bevy_components_workflow/blob/main/examples/bevy_gltf_blueprints/basic_scene_components/src/game/in_game.rs#L23)
I had noted it down as being related to [this](https://github.com/bevyengine/bevy/issues/10436) issue, so it might work on main

**Comment by GitGhillie** [comment]
Hmm I think the fix for that already lives on 0.12.1 :( When I have more time I'll try to make a minimal reproducer without bevy_asset_loader, then I can also easily test against bevy main

**Comment by GitGhillie** [comment]
I moved the discussion about asset loading here btw https://github.com/NiklasEi/bevy_asset_loader/issues/182

**Comment by kaosat-dev** [comment]
Hi @GitGhillie would you mind trying out [this](https://github.com/kaosat-dev/Blender_bevy_components_workflow/pull/134) pr to see if it solve your issues ?

**Comment by kaosat-dev** [comment]
Awesome , thanks for trying it out so quickly !
