### ISSUE TITLE
Update to Bevy 0.13

### ISSUE THREAD

**Issue by kaosat-dev** [kaosat-dev/Blender_bevy_components_workflow#132]
* [x] update all crates & examples to Bevy 0.13

**Comment by franklinblanco** [comment]
Wondering if I could lend a hand here, any of these you'd like help with?

**Comment by kaosat-dev** [comment]
> Wondering if I could lend a hand here, any of these you'd like help with?

Thanks , that would be great ! :) 
I am mostly done code wise, there are still a few things to tweak & double check.
Would you be ok with taking things for a test run & double check things (like the updated READMEs etc) once I am done with that please ?

**Comment by franklinblanco** [comment]
Surely! I'll give it a shot, could you notify me when that's done? Reply here if you want!

**Comment by franklinblanco** [comment]
Hey! I know you didn't tell me yet, I don't know what you have under your sleeve, but I couldn't wait, I forked this and switched to the bevy_main branch and have been using it for a few days. I see no issue Yet!

**Comment by kaosat-dev** [comment]
@franklinblanco thanks a lot for already taking it for a spin :) And very happy to see that it works on your end too !
I have a few things I am still a bit stuck on before I can release:
* [ ] some boilerplate warning from linting (easy to fix)
* [ ] the save/load crate example is completely broken because of certain bugs in Bevy 0.13, tempted to release it regardless
* [ ] I still need to merge the latest batch of changes from main
* [ ] I need to revert some changes I made to the bevy_gltf_blueprints main example, was trying to find workarounds for some of the weird lighting issues in 0.13
* [ ] there are some changes that I would love to include in the release (most are done, only #137 and #133 remain)
