### ISSUE TITLE
Add a `GltfProcessed` marker to objects

### ISSUE THREAD

**Issue by janhohenheim** [kaosat-dev/Blender_bevy_components_workflow#144]
As we discussed in Discord, we currently iterate over all Gltf models on every frame. If we add a `GltfProcessed` marker to the objects after reading their `GltfExtras`, we can constrain the query with a `Without<GltfProcessed>`, which is an archetype and thus makes the query not need to loop over everything.

**Comment by kaosat-dev** [comment]
Agreed !  That is a pattern I often use already to restrict the queries, good fit, simple, efficient.
