### ISSUE TITLE
gltf_auto_export v0.13, does not export animated objects correctly

### ISSUE THREAD

**Issue by kaosat-dev** [kaosat-dev/Blender_bevy_components_workflow#147]

**Comment by kaosat-dev** [comment]
@janhohenheim this is for the issue that you found with the export of the animated objects
Btw, I am experiencing some very weird things: 
![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/587e4516-a29f-4da9-a9b9-a8295e189b4a)
- If I export the root object using the standard gltf exporter (not auto), I also end up with an empty gltf file ???
- Exporting the whole collection (whether the blueprint or an instance), I get a correct gltf file.

**Comment by janhohenheim** [comment]
@kaosat-dev can confirm. I don't know why, but the fox is only exported when you right click the "Fox" collection and "select Objects"
![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/9047632/3bbeed7e-c87e-4eb4-8bce-3af8c5a1ce54)
which results in this gltf
[test.zip](https://github.com/kaosat-dev/Blender_bevy_components_workflow/files/14417979/test.zip)
which can be opened in https://gltf-viewer.donmccurdy.com/ successfully.

Using only the "root", I also get an empty gltf.

**Comment by kaosat-dev** [comment]
@janhohenheim Thanks for the double check! I am not 100% sure it is related, I need to double check the Blender 4.0 release notes. It might have worked until now because of the hack-ish way I was doing things before. (not the first time that a hack works better than clean code in Blender ...)

So this issue is driving me nuts: the best I managed so far is this:
![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/b90cf125-3bc7-43a8-b3b4-8846e3936d1b)

* I can manage to have both the skeleton & the mesh exported
* Regardless of how I try to do the internal "cloning" of the animated mesh, animations are always missing, despite the fact that in python I can see the animation data ??! 

Sorry for the inconvenience, once again !

**Comment by janhohenheim** [comment]
Well, I just started a first person project, so until I need moving NPCs I'm fine, hehe

**Comment by kaosat-dev** [comment]
@janhohenheim haha, all is good then ;)
Joke's on me, I forgot to enable exporting animation in my automated tests :D I will double check things, but I think it should be solve, PR very soon

**Comment by kaosat-dev** [comment]
@janhohenheim the fix & related tests are up ..however, there is something weird going on:
* the animated fox as exported from my own blend file looks like this :
![Screenshot from 2024-02-28 23-09-04](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/b673032c-d6f4-4256-89b7-7855007af8c2)
* when exporting the version from Foxtrot it looks like this:
![Screenshot from 2024-02-28 23-09-15](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/2730a085-2c66-4601-85aa-64c7e9669c42)
When I import (Blender file append) your version into a test blend file, I get the same weird results.
However, I have tried multiple gltf files I found on sketchfab, And I could not reproduce the weirdness:
(all of these have been re-exported using gltf_auto_export, this branch:)

![Screenshot from 2024-02-28 23-40-52](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/25dd081c-bf3a-4889-a6ca-548aed6c178e)
![Screenshot from 2024-02-28 23-51-45](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/7f43f2d0-789e-4e78-8312-3dd5b1d0df41)

Tempted to still merge this PR (as it seems to work in all cases I could muster except for Foxtrot's version of the fox), but if you have some time & any ideas on what is going on, would love to get your feedback

**Comment by janhohenheim** [comment]
Wow that looks... interesting. Yeah, if it works with everything else it should be good enough for a merge. I'll just reimport the fox.
Is it maybe a scaling issue? Have you tried applying all transforms beforehand?

**Comment by kaosat-dev** [comment]
Poor fox indeed:D 
Also , bingo , scaling issue: it seems both our versions have scaling problems , applying transforms does solve **some** of it but not quite :D 
I would still consider it a "not exporter" issue ? (yes, for once I am sorta lazy :D )
![Screen Capture_select-area_20240229101031](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/23cd0132-45f9-4e9c-ab37-71b6610557e5)

**Comment by janhohenheim** [comment]
Haha, great! Yeah, not an exporter issue :)
