### ISSUE TITLE
Documentation clarification.

### ISSUE THREAD

**Issue by blueforesticarus** [kaosat-dev/Blender_bevy_components_workflow#181]
From documentation:

> important : the plugin for processing gltf files runs in update, so you cannot use the components directly if you spawn your scene from gltf in setup (the additional components will not show up)

I'm not sure how to interpret "directly" here. Does this just mean they wont be available *until* the asset is loaded? Or does it mean that scenes spawned in setup will never get processed by bevy_gltf_components?

**Comment by kaosat-dev** [comment]
Hi @blueforesticarus !
It actually means both !
* you need to preload your assets (there are mechanisms to automatically do this, but they are not yet finalised)
* scenes spawned in setup will indeed never get processed by bevy_gltf_components, as the systems run in *update*

**Comment by kaosat-dev** [comment]
Closing issue, if you have more questions about this, do not hesitate to re-open :)
