### ISSUE TITLE
bevy_registry_export dont work :d

### ISSUE THREAD

**Issue by 5-23** [kaosat-dev/Blender_bevy_components_workflow#193]
<img width="1338" alt="image" src="https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/86705803/392073b2-c2d7-4d4f-a230-d813131e298f">

**Comment by tungtose** [comment]
The error message states that bevy_registry_export crate is incompatible with Bevy 0.14. Please use Bevy 0.13 or wait for an update to this crate.

**Comment by 5-23** [comment]
thx XD
