### ISSUE TITLE
gltf_auto_export: Collection instance fallback?

### ISSUE THREAD

**Issue by Azorlogh** [kaosat-dev/Blender_bevy_components_workflow#34]
I'm not sure if it's possible to do this, but can we make it so that collection instances that don't refer to collections not present in the library scenes, get exported as "normal" objects?

The reason for this is that I would like to use Blender's integrated asset browser to populate my main scene, but this creates collection instances.
Since those collections don't live in my Library scene, `bevy_gltf_blueprints` ends up searching for non-existing blueprints and the game crashes.

By the way, thanks a ton for these tools, it's incredibly useful!

**Comment by kaosat-dev** [comment]
Hi @Azorlogh ! 
Very good points and thanks for the PR , taking a long right now.

* about the asset browser:  that one has been on the back of my brain for a while: the whole "library scene" is a sort of stop gap solution for that (with a few advantages): 
     * I am still looking at ways to have change detection for imported assets (I have read some rather contradictory information on that).
     * One of the ideas I had was importing the assets into the library scene and then instancing those :more work, intermediary steps, but might be "good enough"
     * Off the top of my head, perhaps there is a way to "mark" some objects in the main scene as coming from assets, so they are treated like collections and exported correctly as well
 * I want to setup some automated testing for the Python/Blender side as well (soon-ish) , and will include at least one example blend file(s) with asset browser use 
 
And thanks for the kind words, happy that you find it useful :)

**Comment by Azorlogh** [comment]
Ah I see, yeah directly using the asset browser for the blueprints would be nice if it were possible! As long as there's still a way to choose what's a blueprint and what's a regular object from the main scene
