### ISSUE TITLE
Version 0.5.4 won't load in Blender 4.0.1

### ISSUE THREAD

**Issue by BSDGuyShawn** [kaosat-dev/Blender_bevy_components_workflow#69]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 369, in enable
    mod.__time__ = os.path.getmtime(mod.__file__)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\shawn\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\gltf_auto_export.py'

Looklng in that location I see a gltf_auto_export folder with an __init__.py file in it but no sign of a gltf_auto_export.py file in that location or in the directory.

<img width="501" alt="image" src="https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/1402771/d86290d1-0d9f-4d4c-9975-a00a623d636b">

<img width="532" alt="image" src="https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/1402771/7c23bdaa-3d57-4ffb-bfd2-77e3e8f9c1db">

**Comment by BSDGuyShawn** [comment]
Closing and reopening Blender resolves this error. Sorry for the false alarm.

**Comment by kaosat-dev** [comment]
No problem @BSDGuyShawn , I ran into the same issue: it seems Blender does not clear some internal cache, and keeps trying to reference the previous "single file" version
