### ISSUE TITLE
cannot clone entity: component: "bevy_rapier3d::geometry::collider::Collider" is not registered

### ISSUE THREAD

**Issue by czettnersandor** [kaosat-dev/Blender_bevy_components_workflow#84]
I'm using the latest version of bevy_gltf_blueprints (0.5.1) and I'm getting this error as soon as I have one object in a library, instead of on the scene:

```
thread 'main' panicked at /home/sandor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_gltf_blueprints-0.5.1/src/clone_entity.rs:38:57:
cannot clone entity: component: "bevy_rapier3d::geometry::collider::Collider" is not registered
```

I can't register this component, because bevy_rapier3d::geometry::collider is private.

bevy_gltf_components worked. Maybe my .blend file is wrong? I have my colliders set up on the scene, not in the library.

**Comment by kaosat-dev** [comment]
Hi @czettnersandor !
- only registerable components are usable both in ```bevy_gltf_components``` and ```bevy_gltf_blueprints```
- the only difference is, ```bevy_gltf_components``` gives you a **warning** that a given type is not registered (should be in your console), while ```bevy_gltf_blueprints``` will **throw an error**, because of underlying limitation while trying to copy components when they are not registered

For these kind of situations, you need to use proxy components (ie , registrable stand-in components), please take a look at the way this is done in the examples for physics : https://github.com/kaosat-dev/Blender_bevy_components_workflow/blob/main/examples/bevy_gltf_blueprints/basic/src/core/physics/physics_replace_proxies.rs

**Comment by czettnersandor** [comment]
@kaosat-dev thanks for the reply, I already work around my problem and I know about the proxy components. "Collider" is an existing, registered component in my game, taken from the examples.

This was an issue where the library component did not have the custom property, but I set the custom property on the imported collection object (on level scene). In that case, it throws this error. I was not sure if it was a bug, and honestly I'm not even sure now. Perhaps it would be desirable if the scene could only override custom properties that are defined in the library collection object, I don't know. If this is the case, I would throw an error if an instance is trying to override something that's not in the library component, since it will fail anyway.

And thank you for this awesome piece of software, I'm hoping to contribute to it someday if I understand it a little more. It seems to be very useful.

**Comment by kaosat-dev** [comment]
@czettnersandor oh , sorry for the misunderstanding, my bad !
Would you have an example somewhere where I could take a look at ?
Normally you can override custom properties from blueprints at the collection instance level (I use that all the time).

And thank you for the kind words ! :)

**Comment by czettnersandor** [comment]
@kaosat-dev if you create a library collection without any custom properties, then add that collection to the scene and add a custom property in the scene level, you can consistently get the error message. For example, you define a custom property on the scene level:
"Collider", set its value to: "Mesh" (or anything), instead of it's trying to use the "Collider" entity from your code, it will try to add bevy_rapier3d::geometry::collider::Collider, which of course is not registered.

**Comment by kaosat-dev** [comment]
Hi @czettnersandor !
Would you mind trying out v0.6 (just released yesterday) ?
I rewrote the logic of Blueprints spawning significantly, and it looks like it solved your issue:
![Screenshot from 2024-01-11 23-16-15](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/8ba526c3-d7ec-4bec-ae43-85aef6882f31)
![Screenshot from 2024-01-11 23-18-33](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/7571264e-17cf-4dee-b3e9-6c803dc80951)

**Comment by czettnersandor** [comment]
@kaosat-dev I think you meant 0.10. Yes, it resolved the issue, that's great. I upgraded right after I received the notification from GitHub. I no longer define properties on the scene level, but I just tried and it works. But I got a new error. I can no longer save my scene after I added a few planes into it. Probably not related, but it could be. I had this error before, but it went away on the 0.9 version. I somehow resolved this by restarting Blender, but that did not help with 0.10.

I'm getting a new "temp_scene" when I hit save, and this in the console of Blender:
```
Info: Saved "level1.blend"

-------------
changed object Camera
-------------
saved /home/sandor/Projects/jumper/assets/maps/level1.blend
changed_export_parameters False
main scenes ['level1'] library_scenes ['Library']
export_output_folder
EXPORTING
  changed scene level1
--------------
collections:               all: ['Rocks 4', 'Tree', 'Projectile', 'Coin', 'Bush4', 'Frog', 'Tree2', 'Bush1', 'Log3', 'Rocks 1', 'Bush2', 'Ferns', 'Rocks 2', 'Dandelions', 'Log1', 'Bush3', 'Padlock', 'Player', 'Stump1', 'Rocks 3']
collections:           changed: []
collections: not found on disk: []
collections:        in library: ['Scene Collection']
collections:         to export: []
collections:         per_scene: {}
export MAIN scenes
     exporting scene: level1
is object dynamic False <bpy_struct, Object("Camera") at 0x7f946deb4e08>
is object dynamic False <bpy_struct, Object("Light") at 0x7f946ded3a08>
Traceback (most recent call last):
  File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/auto_export.py", line 151, in auto_export
    export_main_scene(bpy.data.scenes[scene_name], folder_path, addon_prefs, library_collections)
  File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/helpers_export.py", line 158, in export_main_scene
    (hollow_scene, temporary_collections, root_objects, special_properties) = generate_hollow_scene(scene, library_collections, addon_prefs, is_object_dynamic)
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/helpers_scenes.py", line 80, in generate_hollow_scene
    copy_hollowed_collection_into(root_collection, copy_root_collection)
  File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/helpers_scenes.py", line 32, in copy_hollowed_collection_into
    if filter is not None and filter(object) is False:
                              ^^^^^^^^^^^^^^
  File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/dynamic.py", line 13, in is_object_dynamic
    collection_name = object.instance_collection.name
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'

EXPORT DONE
Info: Saved "level1.blend"
```

If I add this before line 13 of .config/blender/4.0/scripts/addons/gltf_auto_export/dynamic.py:
```
print(repr(object))
```
I get an additional output of:
```
bpy.data.objects['phonar']
```
phonar is an ordinary object on the scene I did not even change since days ago, and it's only in the "Scene Collection" scene. I wish I could debug this further, but my Python skills end here.

**Comment by czettnersandor** [comment]
After some debugging again, I figured out if I untick "Auto export marked assets" the problem goes away.

**Comment by kaosat-dev** [comment]
> @kaosat-dev I think you meant 0.10. Yes, it resolved the issue, that's great. I upgraded right after I received the notification from GitHub. I no longer define properties on the scene level, but I just tried and it works. But I got a new error. I can no longer save my scene after I added a few planes into it. Probably not related, but it could be. I had this error before, but it went away on the 0.9 version. I somehow resolved this by restarting Blender, but that did not help with 0.10.
> 
> I'm getting a new "temp_scene" when I hit save, and this in the console of Blender:
> 
> ```
> Info: Saved "level1.blend"
> 
> -------------
> changed object Camera
> -------------
> saved /home/sandor/Projects/jumper/assets/maps/level1.blend
> changed_export_parameters False
> main scenes ['level1'] library_scenes ['Library']
> export_output_folder
> EXPORTING
>   changed scene level1
> --------------
> collections:               all: ['Rocks 4', 'Tree', 'Projectile', 'Coin', 'Bush4', 'Frog', 'Tree2', 'Bush1', 'Log3', 'Rocks 1', 'Bush2', 'Ferns', 'Rocks 2', 'Dandelions', 'Log1', 'Bush3', 'Padlock', 'Player', 'Stump1', 'Rocks 3']
> collections:           changed: []
> collections: not found on disk: []
> collections:        in library: ['Scene Collection']
> collections:         to export: []
> collections:         per_scene: {}
> export MAIN scenes
>      exporting scene: level1
> is object dynamic False <bpy_struct, Object("Camera") at 0x7f946deb4e08>
> is object dynamic False <bpy_struct, Object("Light") at 0x7f946ded3a08>
> Traceback (most recent call last):
>   File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/auto_export.py", line 151, in auto_export
>     export_main_scene(bpy.data.scenes[scene_name], folder_path, addon_prefs, library_collections)
>   File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/helpers_export.py", line 158, in export_main_scene
>     (hollow_scene, temporary_collections, root_objects, special_properties) = generate_hollow_scene(scene, library_collections, addon_prefs, is_object_dynamic)
>                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/helpers_scenes.py", line 80, in generate_hollow_scene
>     copy_hollowed_collection_into(root_collection, copy_root_collection)
>   File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/helpers_scenes.py", line 32, in copy_hollowed_collection_into
>     if filter is not None and filter(object) is False:
>                               ^^^^^^^^^^^^^^
>   File "/home/sandor/.config/blender/4.0/scripts/addons/gltf_auto_export/dynamic.py", line 13, in is_object_dynamic
>     collection_name = object.instance_collection.name
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'name'
> 
> EXPORT DONE
> Info: Saved "level1.blend"
> ```
> 
> If I add this before line 13 of .config/blender/4.0/scripts/addons/gltf_auto_export/dynamic.py:
> 
> ```
> print(repr(object))
> ```
> 
> I get an additional output of:
> 
> ```
> bpy.data.objects['phonar']
> ```
> 
> phonar is an ordinary object on the scene I did not even change since days ago, and it's only in the "Scene Collection" scene. I wish I could debug this further, but my Python skills end here.

Thanks for the detailed bug report and the investigating !
That is very weird, the only case where I have seen such issues on the Blender side, was during dev, when some of the add-on parameters changed/where corrupt, and it failed to create one of the "temp scenes" correctly. I will need to take a closer look at that .

- about the "auto export marked assets" did you have that option checked in a project where you have main & library scenes inside the same file ?
- Btw I should have been clearer :)  v0.6 was for ```bevy_gltf_blueprints``` version, not the Blender addon version , which is indeed at v0.10 :)
- I really need to add some tests to the python side (working on it),

**Comment by yiffyrusdev** [comment]
Greetings! I beleive this issue could be a valid one for a related proposal.
First of all - **amazing** work! You are literally lifesaver.

Now straight to the point:

The rapier3d proxy in example of yours here is very nice, what do you think about including it into the crate as a feature?
Many people do use rapier, some components like Collider are "unreflected" [btw Collider is marked "TODO: reflect" :) ]. Would be nice to have them in current workflow as a DRY opt-in.

I've managed to tweak your proxy code for a personal proj (I beleive it is under Apache/MIT as well, right?) a bit to make it a bit more general-purpose, and I want to share.

However, this isn't much, there are several breaking changes and I'm not veeery familiar with bevy/repier yet, the code surely needs a review, so there is no way I'm opening a PR.

If it would make any sense, I'll open related issue.

**Comment by kaosat-dev** [comment]
Hi @yiffyrusdev ! Sorry for the slow reply !
I think it would be very useful (I basically copy & paste the whole proxies boilerplate over to my own projects, not always the best option).
I think it should not be a part of the various existing crates however,  for these reasons:
* not everybody uses Rapier
* I think in the medium/long term bevy_xbpd will be integrated into Bevy itself (there is a lot of things I prefer in xbpd myself, but waiting for it to mature a bit)
* proxies are essentially a stop gap solution for a temporary problem 

Nonetheless, I think it would be nice to offer these as additional crates (plural, because I think each category of proxies should be a separate crate: physics, lighting, etc)
Would you be willing to create these and open a PR here ?
Btw for physics I also have additional "qol" helpers that can generate various colliders from Aabbs (I find them very practical), perhaps I could including them in the existing code for convenience first ?

Curious about skeletons + rigid bodies, don't hesitate to open a seperate issue or a discussion, would love to discuss!

**Comment by kaosat-dev** [comment]
closing this issue as most of the items have been either solved or answered as far as I can tell.
Don't hesitate to re-open if needed.
